const skills = [
  "agile",
  "scrum",
  "jira",
  "confluence",
  "userstories",
  "requirementgathering",
  "stakeholdermanagement",
  "figma",
  "adobexd",
  "wireframing",
  "systemdesign",
  "microservices",
  "designpatterns",
  "responsivedesign",
  "usercentereddesign",
  "javascript",
  "typescript",
  "html",
  "css",
  "react",
  "angular",
  "vue",
  "next.js",
  "redux",
  "webpack",
  "sass",
  "java",
  "python",
  "nodejs",
  "spring",
  "express",
  "rubyonrails",
  "golang",
  "c#",
  ".net",
  "rest",
  "graphql",
  "sql",
  "nosql",
  "mysql",
  "postgresql",
  "mongodb",
  "redis",
  "cassandra",
  "datamodeling",
  "datapipelines",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "gcp",
  "terraform",
  "ansible",
  "ci/cd",
  "jenkins",
  "githubactions",
  "gitlabci",
  "linux",
  "monitoring",
  "prometheus",
  "grafana",
  "selenium",
  "cypress",
  "playwright",
  "junit",
  "mocha",
  "jest",
  "testautomation",
  "manualtesting",
  "performancetesting",
  "versioncontrol",
  "containerization",
  "canarydeployment",
  "bluegreendeployment",
  "logging",
  "splunk",
  "datadog",
  "newrelic",
  "incidentmanagement",
  "reactjs",
  "node",
  "cicd",
  "ci_cd",
  "github",
  "js",
  "ts",
  "py",
  "postgres",
  "mongo",
  "xd",
  "reduxjs",
  "next",
  "jestjs",
  "seleniumweb",
  "manualtest",
  "unittest",
  "gitlabci",
  "githubactions",
  "prom",
  "graf",
];

const role = {
  "Product Manager": [
    "agile",
    "scrum",
    "jira",
    "confluence",
    "userstories",
    "requirementgathering",
    "stakeholdermanagement",
  ],
  "UX/UI Designer": [
    "figma",
    "adobexd",
    "wireframing",
    "responsivedesign",
    "usercentereddesign",
  ],
  "Software Architect": ["systemdesign", "microservices", "designpatterns"],
  "Frontend Developer": [
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "next.js",
    "redux",
    "webpack",
    "sass",
    "graphql",
    "rest",
    "git",
  ],
  "Backend Developer": [
    "java",
    "python",
    "nodejs",
    "spring",
    "express",
    "rubyonrails",
    "golang",
    "c#",
    ".net",
    "sql",
    "nosql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "cassandra",
    "rest",
    "graphql",
    "git",
  ],
  "Full Stack Developer": [
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "nodejs",
    "java",
    "python",
    "sql",
    "nosql",
    "rest",
    "graphql",
    "git",
  ],
  "Data Engineer": [
    "python",
    "sql",
    "nosql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "cassandra",
    "datamodeling",
    "datapipelines",
    "aws",
    "linux",
  ],
  "DevOps Engineer": [
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "terraform",
    "ansible",
    "ci/cd",
    "jenkins",
    "githubactions",
    "gitlabci",
    "linux",
    "monitoring",
    "prometheus",
    "grafana",
    "git",
  ],
  "Cloud Engineer": ["aws", "azure", "gcp", "docker", "kubernetes", "linux"],
  "QA Engineer": [
    "selenium",
    "cypress",
    "playwright",
    "junit",
    "mocha",
    "jest",
    "testautomation",
    "manualtesting",
    "performancetesting",
  ],
  "Agile Practitioner": [
    "agile",
    "scrum",
    "jira",
    "confluence",
    "git",
    "ci/cd",
  ],
  "Site Reliability Engineer": [
    "monitoring",
    "prometheus",
    "grafana",
    "logging",
    "splunk",
    "datadog",
    "newrelic",
    "incidentmanagement",
    "linux",
  ],
};

const skillAliasMap = {
  reactjs: "react",
  react: "react",
  node: "nodejs",
  nodejs: "nodejs",
  cicd: "ci/cd",
  ci_cd: "ci/cd",
  github: "git",
  git: "git",
  js: "javascript",
  ts: "typescript",
  py: "python",
  postgres: "postgresql",
  mongo: "mongodb",
  gcp: "gcp",
  xd: "adobexd",
  reduxjs: "redux",
  next: "next.js",
  jestjs: "jest",
  seleniumweb: "selenium",
  manualtest: "manualtesting",
  unittest: "junit",
  gitlabci: "gitlabci",
  githubactions: "githubactions",
  prom: "prometheus",
  graf: "grafana",
};

const experience = ["years"];

const keywords = [
  "team",
  "teamwork",
  "communicate",
  "communication",
  "leadership",
  "leader",
  "collaboration",
  "collaborative",
  "problem-solving",
  "initiative",
  "ownership",
  "adaptability",
  "flexibility",
  "critical thinking",
  "analytical",
  "creative thinking",
  "innovation",
  "attention to detail",
  "detail-oriented",
  "deadline-driven",
  "time management",
  "organization",
  "responsibility",
  "accountability",
  "fast-paced",
  "independent",
  "self-motivated",
  "mentor",
  "coaching",
  "stakeholders",
  "stakeholder engagement",
  "cross-functional",
  "emotional intelligence",
  "decision-making",
  "conflict resolution",
  "active listening",
  "negotiation",
  "strategic thinking",
  "results-oriented",
  "growth mindset",
  "resilience",
  "multitasking",
  "prioritization",
  "work ethic",
  "professionalism",
  "customer-focused",
];

export const scoreCategories = {
  skills,
  experience,
  keywords,
  role,
  skillAliasMap,
};
