const skills = [
  "javascript",
  "java",
  "nodejs",
  "node",
  "python",
  "typescript",
  "react",
  "reactjs",
  "angular",
  "vue",
  "spring",
  "express",
  "sql",
  "nosql",
  "mongodb",
  "postgresql",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "git",
  "ci/cd",
  "rest",
  "graphql",
  "html",
  "css",
  "linux",
  "agile",
  "scrum",
];

const skillAliasMap = {
  reactjs: "react",
  react: "react",
  node: "nodejs",
  nodejs: "nodejs",
  cicd: "ci/cd",
  ci_cd: "ci/cd",
  github: "git",
  git: "git",
  js: "javascript",
  ts: "typescript",
  py: "python",
  postgres: "postgresql",
  mongo: "mongodb",
};

const experience = ["years"];

const keywords = [
  "team",
  "communicate",
  "leader",
  "collaboration",
  "problem-solving",
  "initiative",
  "ownership",
  "adaptability",
  "critical thinking",
  "analytical",
  "detail-oriented",
  "deadline-driven",
  "responsibility",
  "fast-paced",
  "independent",
  "mentor",
  "stakeholders",
  "cross-functional",
];

const role = {
  "Frontend Developer": [
    "javascript",
    "typescript",
    "react",
    "angular",
    "vue",
    "html",
    "css",
    "graphql",
    "rest",
    "git",
  ],
  "Backend Developer": [
    "java",
    "nodejs",
    "python",
    "spring",
    "express",
    "sql",
    "nosql",
    "mongodb",
    "postgresql",
    "rest",
    "graphql",
    "git",
  ],
  "DevOps Engineer": [
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "ci/cd",
    "linux",
    "git",
  ],
  "Cloud Engineer": ["aws", "azure", "docker", "kubernetes", "linux"],
  "Data Engineer": [
    "python",
    "sql",
    "nosql",
    "mongodb",
    "postgresql",
    "aws",
    "linux",
  ],
  "Agile Practitioner": ["agile", "scrum", "git", "ci/cd"],
};

export const scoreCategories = {
  skills,
  experience,
  keywords,
  role,
  skillAliasMap,
};
